// WYDN Robotics Lab JS
function func1(){ console.log('Function 1 loaded'); }
function func2(){ console.log('Function 2 loaded'); }
function func3(){ console.log('Function 3 loaded'); }
function func4(){ console.log('Function 4 loaded'); }
function func5(){ console.log('Function 5 loaded'); }
function func6(){ console.log('Function 6 loaded'); }
function func7(){ console.log('Function 7 loaded'); }
function func8(){ console.log('Function 8 loaded'); }
function func9(){ console.log('Function 9 loaded'); }
function func10(){ console.log('Function 10 loaded'); }
function func11(){ console.log('Function 11 loaded'); }
function func12(){ console.log('Function 12 loaded'); }
function func13(){ console.log('Function 13 loaded'); }
function func14(){ console.log('Function 14 loaded'); }
function func15(){ console.log('Function 15 loaded'); }
function func16(){ console.log('Function 16 loaded'); }
function func17(){ console.log('Function 17 loaded'); }
function func18(){ console.log('Function 18 loaded'); }
function func19(){ console.log('Function 19 loaded'); }
function func20(){ console.log('Function 20 loaded'); }
function func21(){ console.log('Function 21 loaded'); }
function func22(){ console.log('Function 22 loaded'); }
function func23(){ console.log('Function 23 loaded'); }
function func24(){ console.log('Function 24 loaded'); }
function func25(){ console.log('Function 25 loaded'); }
function func26(){ console.log('Function 26 loaded'); }
function func27(){ console.log('Function 27 loaded'); }
function func28(){ console.log('Function 28 loaded'); }
function func29(){ console.log('Function 29 loaded'); }
function func30(){ console.log('Function 30 loaded'); }
function func31(){ console.log('Function 31 loaded'); }
function func32(){ console.log('Function 32 loaded'); }
function func33(){ console.log('Function 33 loaded'); }
function func34(){ console.log('Function 34 loaded'); }
function func35(){ console.log('Function 35 loaded'); }
function func36(){ console.log('Function 36 loaded'); }
function func37(){ console.log('Function 37 loaded'); }
function func38(){ console.log('Function 38 loaded'); }
function func39(){ console.log('Function 39 loaded'); }
function func40(){ console.log('Function 40 loaded'); }
function func41(){ console.log('Function 41 loaded'); }
function func42(){ console.log('Function 42 loaded'); }
function func43(){ console.log('Function 43 loaded'); }
function func44(){ console.log('Function 44 loaded'); }
function func45(){ console.log('Function 45 loaded'); }
function func46(){ console.log('Function 46 loaded'); }
function func47(){ console.log('Function 47 loaded'); }
function func48(){ console.log('Function 48 loaded'); }
function func49(){ console.log('Function 49 loaded'); }
function func50(){ console.log('Function 50 loaded'); }
function func51(){ console.log('Function 51 loaded'); }
function func52(){ console.log('Function 52 loaded'); }
function func53(){ console.log('Function 53 loaded'); }
function func54(){ console.log('Function 54 loaded'); }
function func55(){ console.log('Function 55 loaded'); }
function func56(){ console.log('Function 56 loaded'); }
function func57(){ console.log('Function 57 loaded'); }
function func58(){ console.log('Function 58 loaded'); }
function func59(){ console.log('Function 59 loaded'); }
function func60(){ console.log('Function 60 loaded'); }
function func61(){ console.log('Function 61 loaded'); }
function func62(){ console.log('Function 62 loaded'); }
function func63(){ console.log('Function 63 loaded'); }
function func64(){ console.log('Function 64 loaded'); }
function func65(){ console.log('Function 65 loaded'); }
function func66(){ console.log('Function 66 loaded'); }
function func67(){ console.log('Function 67 loaded'); }
function func68(){ console.log('Function 68 loaded'); }
function func69(){ console.log('Function 69 loaded'); }
function func70(){ console.log('Function 70 loaded'); }
function func71(){ console.log('Function 71 loaded'); }
function func72(){ console.log('Function 72 loaded'); }
function func73(){ console.log('Function 73 loaded'); }
function func74(){ console.log('Function 74 loaded'); }
function func75(){ console.log('Function 75 loaded'); }
function func76(){ console.log('Function 76 loaded'); }
function func77(){ console.log('Function 77 loaded'); }
function func78(){ console.log('Function 78 loaded'); }
function func79(){ console.log('Function 79 loaded'); }
function func80(){ console.log('Function 80 loaded'); }
function func81(){ console.log('Function 81 loaded'); }
function func82(){ console.log('Function 82 loaded'); }
function func83(){ console.log('Function 83 loaded'); }
function func84(){ console.log('Function 84 loaded'); }
function func85(){ console.log('Function 85 loaded'); }
function func86(){ console.log('Function 86 loaded'); }
function func87(){ console.log('Function 87 loaded'); }
function func88(){ console.log('Function 88 loaded'); }
function func89(){ console.log('Function 89 loaded'); }
function func90(){ console.log('Function 90 loaded'); }
function func91(){ console.log('Function 91 loaded'); }
function func92(){ console.log('Function 92 loaded'); }
function func93(){ console.log('Function 93 loaded'); }
function func94(){ console.log('Function 94 loaded'); }
function func95(){ console.log('Function 95 loaded'); }
function func96(){ console.log('Function 96 loaded'); }
function func97(){ console.log('Function 97 loaded'); }
function func98(){ console.log('Function 98 loaded'); }
function func99(){ console.log('Function 99 loaded'); }
function func100(){ console.log('Function 100 loaded'); }
function func101(){ console.log('Function 101 loaded'); }
function func102(){ console.log('Function 102 loaded'); }
function func103(){ console.log('Function 103 loaded'); }
function func104(){ console.log('Function 104 loaded'); }
function func105(){ console.log('Function 105 loaded'); }
function func106(){ console.log('Function 106 loaded'); }
function func107(){ console.log('Function 107 loaded'); }
function func108(){ console.log('Function 108 loaded'); }
function func109(){ console.log('Function 109 loaded'); }
function func110(){ console.log('Function 110 loaded'); }
function func111(){ console.log('Function 111 loaded'); }
function func112(){ console.log('Function 112 loaded'); }
function func113(){ console.log('Function 113 loaded'); }
function func114(){ console.log('Function 114 loaded'); }
function func115(){ console.log('Function 115 loaded'); }
function func116(){ console.log('Function 116 loaded'); }
function func117(){ console.log('Function 117 loaded'); }
function func118(){ console.log('Function 118 loaded'); }
function func119(){ console.log('Function 119 loaded'); }
function func120(){ console.log('Function 120 loaded'); }
function func121(){ console.log('Function 121 loaded'); }
function func122(){ console.log('Function 122 loaded'); }
function func123(){ console.log('Function 123 loaded'); }
function func124(){ console.log('Function 124 loaded'); }
function func125(){ console.log('Function 125 loaded'); }
function func126(){ console.log('Function 126 loaded'); }
function func127(){ console.log('Function 127 loaded'); }
function func128(){ console.log('Function 128 loaded'); }
function func129(){ console.log('Function 129 loaded'); }
function func130(){ console.log('Function 130 loaded'); }
function func131(){ console.log('Function 131 loaded'); }
function func132(){ console.log('Function 132 loaded'); }
function func133(){ console.log('Function 133 loaded'); }
function func134(){ console.log('Function 134 loaded'); }
function func135(){ console.log('Function 135 loaded'); }
function func136(){ console.log('Function 136 loaded'); }
function func137(){ console.log('Function 137 loaded'); }
function func138(){ console.log('Function 138 loaded'); }
function func139(){ console.log('Function 139 loaded'); }
function func140(){ console.log('Function 140 loaded'); }
function func141(){ console.log('Function 141 loaded'); }
function func142(){ console.log('Function 142 loaded'); }
function func143(){ console.log('Function 143 loaded'); }
function func144(){ console.log('Function 144 loaded'); }
function func145(){ console.log('Function 145 loaded'); }
function func146(){ console.log('Function 146 loaded'); }
function func147(){ console.log('Function 147 loaded'); }
function func148(){ console.log('Function 148 loaded'); }
function func149(){ console.log('Function 149 loaded'); }
function func150(){ console.log('Function 150 loaded'); }
function func151(){ console.log('Function 151 loaded'); }
function func152(){ console.log('Function 152 loaded'); }
function func153(){ console.log('Function 153 loaded'); }
function func154(){ console.log('Function 154 loaded'); }
function func155(){ console.log('Function 155 loaded'); }
function func156(){ console.log('Function 156 loaded'); }
function func157(){ console.log('Function 157 loaded'); }
function func158(){ console.log('Function 158 loaded'); }
function func159(){ console.log('Function 159 loaded'); }
function func160(){ console.log('Function 160 loaded'); }
function func161(){ console.log('Function 161 loaded'); }
function func162(){ console.log('Function 162 loaded'); }
function func163(){ console.log('Function 163 loaded'); }
function func164(){ console.log('Function 164 loaded'); }
function func165(){ console.log('Function 165 loaded'); }
function func166(){ console.log('Function 166 loaded'); }
function func167(){ console.log('Function 167 loaded'); }
function func168(){ console.log('Function 168 loaded'); }
function func169(){ console.log('Function 169 loaded'); }
function func170(){ console.log('Function 170 loaded'); }
function func171(){ console.log('Function 171 loaded'); }
function func172(){ console.log('Function 172 loaded'); }
function func173(){ console.log('Function 173 loaded'); }
function func174(){ console.log('Function 174 loaded'); }
function func175(){ console.log('Function 175 loaded'); }
function func176(){ console.log('Function 176 loaded'); }
function func177(){ console.log('Function 177 loaded'); }
function func178(){ console.log('Function 178 loaded'); }
function func179(){ console.log('Function 179 loaded'); }
function func180(){ console.log('Function 180 loaded'); }
function func181(){ console.log('Function 181 loaded'); }
function func182(){ console.log('Function 182 loaded'); }
function func183(){ console.log('Function 183 loaded'); }
function func184(){ console.log('Function 184 loaded'); }
function func185(){ console.log('Function 185 loaded'); }
function func186(){ console.log('Function 186 loaded'); }
function func187(){ console.log('Function 187 loaded'); }
function func188(){ console.log('Function 188 loaded'); }
function func189(){ console.log('Function 189 loaded'); }
function func190(){ console.log('Function 190 loaded'); }
function func191(){ console.log('Function 191 loaded'); }
function func192(){ console.log('Function 192 loaded'); }
function func193(){ console.log('Function 193 loaded'); }
function func194(){ console.log('Function 194 loaded'); }
function func195(){ console.log('Function 195 loaded'); }
function func196(){ console.log('Function 196 loaded'); }
function func197(){ console.log('Function 197 loaded'); }
function func198(){ console.log('Function 198 loaded'); }
function func199(){ console.log('Function 199 loaded'); }
function func200(){ console.log('Function 200 loaded'); }
function func201(){ console.log('Function 201 loaded'); }
function func202(){ console.log('Function 202 loaded'); }
function func203(){ console.log('Function 203 loaded'); }
function func204(){ console.log('Function 204 loaded'); }
function func205(){ console.log('Function 205 loaded'); }
function func206(){ console.log('Function 206 loaded'); }
function func207(){ console.log('Function 207 loaded'); }
function func208(){ console.log('Function 208 loaded'); }
function func209(){ console.log('Function 209 loaded'); }
function func210(){ console.log('Function 210 loaded'); }
function func211(){ console.log('Function 211 loaded'); }
function func212(){ console.log('Function 212 loaded'); }
function func213(){ console.log('Function 213 loaded'); }
function func214(){ console.log('Function 214 loaded'); }
function func215(){ console.log('Function 215 loaded'); }
function func216(){ console.log('Function 216 loaded'); }
function func217(){ console.log('Function 217 loaded'); }
function func218(){ console.log('Function 218 loaded'); }
function func219(){ console.log('Function 219 loaded'); }
function func220(){ console.log('Function 220 loaded'); }
function func221(){ console.log('Function 221 loaded'); }
function func222(){ console.log('Function 222 loaded'); }
function func223(){ console.log('Function 223 loaded'); }
function func224(){ console.log('Function 224 loaded'); }
function func225(){ console.log('Function 225 loaded'); }
function func226(){ console.log('Function 226 loaded'); }
function func227(){ console.log('Function 227 loaded'); }
function func228(){ console.log('Function 228 loaded'); }
function func229(){ console.log('Function 229 loaded'); }
function func230(){ console.log('Function 230 loaded'); }
function func231(){ console.log('Function 231 loaded'); }
function func232(){ console.log('Function 232 loaded'); }
function func233(){ console.log('Function 233 loaded'); }
function func234(){ console.log('Function 234 loaded'); }
function func235(){ console.log('Function 235 loaded'); }
function func236(){ console.log('Function 236 loaded'); }
function func237(){ console.log('Function 237 loaded'); }
function func238(){ console.log('Function 238 loaded'); }
function func239(){ console.log('Function 239 loaded'); }
function func240(){ console.log('Function 240 loaded'); }
function func241(){ console.log('Function 241 loaded'); }
function func242(){ console.log('Function 242 loaded'); }
function func243(){ console.log('Function 243 loaded'); }
function func244(){ console.log('Function 244 loaded'); }
function func245(){ console.log('Function 245 loaded'); }
function func246(){ console.log('Function 246 loaded'); }
function func247(){ console.log('Function 247 loaded'); }
function func248(){ console.log('Function 248 loaded'); }
function func249(){ console.log('Function 249 loaded'); }

function addToCart(id){
fetch('add_cart.php',{
method:'POST',
headers:{'Content-Type':'application/x-www-form-urlencoded'},
body:'id='+id
}).then(()=>alert('Added to Cart'));
}
